name: Arduino CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run arduino-builder for pylon.ino
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketch: /pylon/pylon.ino
    - name: Run arduino-builder for base.ino
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketch: /base/base.ino
