name: Arduino CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run arduino-builder for pylon.ino
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketchDirectory: /pylon
    - name: Run arduino-builder for base.ino
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketchDirectory: /base
